name: Deploy React App via SSH

on:
  push:
    branches:
      - React
  workflow_dispatch: 
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci

      - name: Build React app
        run: npm run build

      - name: Deploy via SSH
        uses: burnett01/rsync-deployments@7.0.2
        with: 
          switches: -avzr --delete
          path: src/
          remote_path: ${{ secrets.FTP_TARGET_DIR }}
          remote_host: ygopricecheck.nz
          remote_user: ygoprice
          remote_key: ${{ secrets.SSH_KEY }}
          remote_key_pass: ${{ secrets.FTP_PASSWORD }}
