name: Deploy React App via SSH

on:
  push:
    branches:
      - React
  workflow_dispatch: 
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci

      - name: Build React app
        run: npm run build

      - name: Deploy via SSH
        uses: SamKirkland/web-deploy@v1
        with: 
          target-server: ygopricecheck.nz
          remote-user: ygoprice
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: ${{ secrets.FTP_TARGET_DIR }}
